sudo: required
language: node_js
node_js:
  - "11"
services:
  - docker
install:
  - npm  install
cache:
  directories:
    - node_modules
script:
  - source ./setPath
  - docker login --username maty21 --password ${DOCKER_HUB_PASS}
  - docker build -t maty21/pro-club-ui${TRAVIS_COMMIT} .
  - docker push maty21/pro-club-ui${TRAVIS_COMMIT}
